from pyrogram import Client, filters
from pyrogram.types import Message
import time

# ---------- CONFIG ----------
API_ID = 29680263           # Telegram API ID
API_HASH = "a251c8203284c9fe7812f418ec8aa3a9"
SESSION = "my_account"     # Pyrogram session নাম
OWNER_ID = 6577308099       # তোমার numeric Telegram ID
COOLDOWN_SECONDS = 300     # ৫ মিনিট cooldown

# ---------- OFFLINE MESSAGE (MarkdownV2) ----------
OFFLINE_MSG = (
    "💭 *I’m offline for a while...*\n"
    "_No replies, no calls — just a little peace & silence._\n"
    "If it’s important, leave your message... I’ll be back when I’m meant to. 🌙\n\n"
    "`This text was automatically generated by Docker`"
)

# ---------- VARIABLES ----------
sleep_mode = False
cooldowns = {}  # user_id : last_active_time

# ---------- INIT ----------
app = Client(
    SESSION,
    api_id=API_ID,
    api_hash=API_HASH
)

# ===== COMMANDS =====
@app.on_message(filters.command("sleep") & filters.user(OWNER_ID))
async def activate_sleep(_, msg: Message):
    global sleep_mode
    sleep_mode = True
    await msg.reply_text("😴 *Sleep mode activated.* Auto-reply is now *ON*.", parse_mode="markdown_v2")

@app.on_message(filters.command("off") & filters.user(OWNER_ID))
async def deactivate_sleep(_, msg: Message):
    global sleep_mode
    sleep_mode = False
    await msg.reply_text("☀️ *Sleep mode deactivated.* Auto-reply is now *OFF*.", parse_mode="markdown_v2")

@app.on_message(filters.command("status") & filters.user(OWNER_ID))
async def status_check(_, msg: Message):
    status = "🟢 ON" if sleep_mode else "🔴 OFF"
    await msg.reply_text(f"🛰️ *Auto-Reply Status:* {status}", parse_mode="markdown_v2")

# ===== MARK SELF ACTIVE =====
@app.on_message(filters.me)
async def mark_active(_, msg: Message):
    """যখন তুমি নিজে মেসেজ পাঠাবে, ওই ইউজারের জন্য ৫ মিনিট auto-reply বন্ধ থাকবে।"""
    cooldowns[msg.chat.id] = time.time()

# ===== AUTO-REPLY =====
@app.on_message(filters.private | filters.group)
async def auto_reply(_, msg: Message):
    global sleep_mode
    if not sleep_mode:
        return

    # নিজের মেসেজ বাদ
    if msg.from_user and msg.from_user.is_self:
        return

    # বট বাদ
    if msg.from_user and msg.from_user.is_bot:
        return

    # গ্রুপে mention ছাড়া skip
    if msg.chat.type in ["supergroup", "group"] and not msg.mentioned:
        return

    try:
        user_id = msg.chat.id
        now = time.time()
        last_time = cooldowns.get(user_id, 0)

        # ৫ মিনিট cooldown চেক
        if now - last_time < COOLDOWN_SECONDS:
            return

        cooldowns[user_id] = now

        # Auto-reply
        await msg.reply_text(OFFLINE_MSG, parse_mode="markdown_v2")

    except Exception as e:
        print("⚠️ Auto-reply skipped due to:", e)

# ===== MAIN =====
if __name__ == "__main__":
    print("🤖 Userbot running in background... Use /sleep, /off, /status from your Telegram account.")
    app.run()
